# Goreleaser configuration for whaletui
# Automatically handles versioning, building, and releasing

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm64
      - ppc64le
      - s390x
    ignore:
      - goos: darwin
        goarch: arm64
        goarm: "7"
      - goos: windows
        goarch: ppc64le
      - goos: darwin
        goarch: ppc64le
      - goos: freebsd
        goarch: ppc64le
      - goos: windows
        goarch: s390x
      - goos: darwin
        goarch: s390x
      - goos: freebsd
        goarch: s390x
      - goos: darwin
        goarch: "386"
    ldflags:
      - -s -w
      - -X github.com/wikczerski/whaletui/cmd.Version={{.Version}}
      - -X github.com/wikczerski/whaletui/cmd.CommitSHA={{.Commit}}
      - -X github.com/wikczerski/whaletui/cmd.BuildDate={{.Date}}
    binary: whaletui

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README*
      - LICENSE*
      - CHANGELOG*
      - docs/*
      - configs/*

nfpms:
  - maintainer: "whaletui <22891046+wikczerski@users.noreply.github.com>"
    description: "whaletui - Docker Container Management Tool"
    homepage: "https://github.com/wikczerski/whaletui"
    license: "MIT"
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      - src: "README.md"
        dst: /usr/share/doc/whaletui/README.md
      - src: "LICENSE"
        dst: /usr/share/doc/whaletui/LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: wikczerski
    name: whaletui
  draft: false
  prerelease: false
  name_template: 'v{{ .Version }}'
  footer: |
    ### 📚 Additional Resources

    - **Documentation**: [GitHub Repository](https://github.com/wikczerski/whaletui)
    - **Issues**: [Report Bugs](https://github.com/wikczerski/whaletui/issues)
    - **Discussions**: [Community Support](https://github.com/wikczerski/whaletui/discussions)

    ---

    **Enjoy using whaletui! 🐳✨**

brews:
  - name: whaletui
    homepage: "https://github.com/wikczerski/whaletui"
    description: "Docker CLI Dashboard"
    repository:
      name: whaletui
      owner: wikczerski
    commit_author:
      name: "Goreleaser Bot"
      email: "bot@goreleaser.com"
    goarm: "6"
    test: |
      system "#{bin}/whaletui", "--help"
    install: |
      bin.install "whaletui" => "whaletui"
