# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whaletui < Formula
  desc "Docker CLI Dashboard"
  homepage "https://github.com/wikczerski/whaletui"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/wikczerski/whaletui/releases/download/v0.1.0/whaletui_v0.1.0_Darwin_x86_64.tar.gz"
      sha256 "d4889378d441d347d789bb8fa1baadac3c12c4f8358dd82698be478dada863e6"

      def install
        bin.install "whaletui" => "whaletui"
      end
    end
    on_arm do
      url "https://github.com/wikczerski/whaletui/releases/download/v0.1.0/whaletui_v0.1.0_Darwin_arm64.tar.gz"
      sha256 "ed9608edf788e02e0a461b7f44f5c1d6e649079f7a145867362a45fef77b5fac"

      def install
        bin.install "whaletui" => "whaletui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wikczerski/whaletui/releases/download/v0.1.0/whaletui_v0.1.0_Linux_x86_64.tar.gz"
        sha256 "8eba75adc891e98ba761b5a4763a5df172306fd9d94e8b28ed025fec4f407d8d"

        def install
          bin.install "whaletui" => "whaletui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wikczerski/whaletui/releases/download/v0.1.0/whaletui_v0.1.0_Linux_arm64.tar.gz"
        sha256 "d87f857f54fc877c2f6c9f297f9792be5c30fea53b8a5961d960b5e03fae8ba6"

        def install
          bin.install "whaletui" => "whaletui"
        end
      end
    end
  end

  test do
    system "#{bin}/whaletui", "--help"
  end
end
