colors:
  header: "#00FF00"     # Bright green header
  border: "#444444"     # Dark gray borders
  text: "#E0E0E0"       # Light gray text
  background: "black"   # Black background
  success: "#00FF00"    # Bright green success
  warning: "#FFFF00"    # Bright yellow warning
  error: "#FF0000"      # Bright red error
  info: "#0080FF"       # Bright blue info

shell:
  border: "#444444"     # Dark gray borders (matching theme)
  title: "#00FF00"      # Bright green title (matching header)
  text: "#E0E0E0"       # Light gray text (matching theme)
  background: "black"   # Black background (matching theme)
  cmd:
    label: "#00FF00"      # Bright green label (matching success)
    border: "#444444"     # Dark gray border (matching theme)
    text: "#E0E0E0"       # Light gray text (matching theme)
    background: "black"   # Black background (matching theme)
    placeholder: "#666666" # Medium gray placeholder

containerExec:
  label: "#00FF00"      # Bright green label (matching header)
  border: "#444444"     # Dark gray border (matching theme)
  text: "#E0E0E0"       # Light gray text (matching theme)
  background: "#222222" # Very dark gray background
  placeholder: "#666666" # Medium gray placeholder (matching shell)
  title: "#00FF00"      # Bright green title (matching header)

commandMode:
  label: "#00FF00"      # Bright green label (matching header)
  border: "#444444"     # Dark gray border (matching theme)
  text: "#E0E0E0"       # Light gray text (matching theme)
  background: "#222222" # Very dark gray background
  placeholder: "#666666" # Medium gray placeholder (matching shell)
  title: "#00FF00"      # Bright green title (matching header)

# Table column configurations with percentage-based widths
tableLimits:
  views:
    containers:
      columns:
        id:
          limit: 12
          width_percent: 12      # 20% of terminal width
          min_width: 12          # Minimum 12 characters
          max_width: 30          # Maximum 30 characters
          visible: true
          alignment: "left"
          display_name: "Container ID"
        name:
          limit: 25
          width_percent: 25      # 25% of terminal width
          min_width: 15          # Minimum 15 characters
          max_width: 40          # Maximum 40 characters
          visible: true
          alignment: "left"
          display_name: "Name"
        image:
          limit: 35
          width_percent: 30      # 30% of terminal width
          min_width: 20          # Minimum 20 characters
          max_width: 50          # Maximum 50 characters
          visible: true
          alignment: "left"
          display_name: "Image"
        status:
          limit: 20
          width_percent: 15      # 15% of terminal width
          min_width: 8           # Minimum 8 characters
          max_width: 20          # Maximum 20 characters
          visible: true
          alignment: "right"
          display_name: "Status"
        state:
          limit: 15
          width_percent: 10      # 10% of terminal width
          min_width: 6           # Minimum 6 characters
          max_width: 15          # Maximum 15 characters
          visible: true
          alignment: "right"
          display_name: "State"
        ports:
          limit: 25
          width_percent: 25      # 25% of terminal width
          min_width: 15          # Minimum 15 characters
          max_width: 40          # Maximum 40 characters
          visible: true
          alignment: "right"
          display_name: "Ports"
        created:
          limit: 25
          width_percent: 15      # 25% of terminal width
          min_width: 15          # Minimum 15 characters
          max_width: 40          # Maximum 40 characters
          visible: true
          alignment: "right"
          display_name: "Created"

    images:
      columns:
        id:
          limit: 12
          width_percent: 15      # 15% of terminal width
          min_width: 10          # Minimum 10 characters
          max_width: 20          # Maximum 20 characters
          visible: true
          alignment: "left"
          display_name: "Image ID"
        repository:
          limit: 40
          width_percent: 38      # 45% of terminal width
          min_width: 25          # Minimum 25 characters
          max_width: 70          # Maximum 70 characters
          visible: true
          alignment: "left"
          display_name: "Repository"
        tag:
          limit: 20
          width_percent: 10
          min_width: 10
          max_width: 30
          visible: true
          alignment: "left"
          display_name: "Tag"
        size:
          limit: 15
          width_percent: 15      # 15% of terminal width
          min_width: 10          # Minimum 10 characters
          max_width: 20          # Maximum 20 characters
          visible: true
          alignment: "right"
          display_name: "Size"
        created:
          limit: 30
          width_percent: 20      # 20% of terminal width
          min_width: 15          # Minimum 15 characters
          max_width: 30          # Maximum 30 characters
          visible: true
          alignment: "right"
          display_name: "Created"

    volumes:
      columns:
        name:
          limit: 30
          width_percent: 35      # 35% of terminal width
          min_width: 20          # Minimum 20 characters
          max_width: 50          # Maximum 50 characters
          visible: true
          alignment: "left"
          display_name: "Volume Name"
        driver:
          limit: 15
          width_percent: 15      # 15% of terminal width
          min_width: 10          # Minimum 10 characters
          max_width: 25          # Maximum 25 characters
          visible: true
          alignment: "left"
          display_name: "Driver"
        mountpoint:
          limit: 50
          width_percent: 50      # 50% of terminal width
          min_width: 30          # Minimum 30 characters
          max_width: 80          # Maximum 80 characters
          visible: true
          alignment: "left"
          display_name: "Mount Point"
        created:
          limit: 25
          width_percent: 15      # 25% of terminal width
          min_width: 15          # Minimum 15 characters
          max_width: 40          # Maximum 40 characters
          visible: true
          alignment: "right"
          display_name: "Created"
        size:
          limit: 15
          width_percent: 15      # 15% of terminal width
          min_width: 10          # Minimum 10 characters
          max_width: 20          # Maximum 20 characters
          visible: true
          alignment: "right"
          display_name: "Size"

    networks:
      columns:
        id:
          limit: 12
          width_percent: 15      # 15% of terminal width
          min_width: 10          # Minimum 10 characters
          max_width: 20          # Maximum 20 characters
          visible: true
          alignment: "left"
          display_name: "Network ID"
        name:
          limit: 25
          width_percent: 30      # 30% of terminal width
          min_width: 15          # Minimum 15 characters
          max_width: 40          # Maximum 40 characters
          visible: true
          alignment: "left"
          display_name: "Network Name"
        driver:
          limit: 15
          width_percent: 15      # 15% of terminal width
          min_width: 10          # Minimum 10 characters
          max_width: 25          # Maximum 25 characters
          visible: true
          alignment: "left"
          display_name: "Driver"
        scope:
          limit: 10
          width_percent: 10      # 10% of terminal width
          min_width: 6           # Minimum 6 characters
          max_width: 15          # Maximum 15 characters
          visible: true
          alignment: "center"
          display_name: "Scope"
        created:
          limit: 25
          width_percent: 15      # 25% of terminal width
          min_width: 15          # Minimum 15 characters
          max_width: 40          # Maximum 40 characters
          visible: true
          alignment: "right"
          display_name: "Created"
        subnet:
          limit: 20
          width_percent: 25      # 25% of terminal width
          min_width: 15          # Minimum 15 characters
          max_width: 35          # Maximum 35 characters
          visible: true
          alignment: "left"
          display_name: "Subnet"
        gateway:
          limit: 20
          width_percent: 20      # 20% of terminal width
          min_width: 15          # Minimum 15 characters
          max_width: 30          # Maximum 30 characters
          visible: true
          alignment: "left"
          display_name: "Gateway"

    "Swarm Nodes":
      columns:
        id:
          limit: 12
          width_percent: 15      # 15% of terminal width
          min_width: 10          # Minimum 10 characters
          max_width: 20          # Maximum 20 characters
          visible: true
          alignment: "left"
          display_name: "Node ID"
        name:
          limit: 25
          width_percent: 25      # 25% of terminal width
          min_width: 15          # Minimum 15 characters
          max_width: 40          # Maximum 40 characters
          visible: true
          alignment: "left"
          display_name: "Node Name"
        status:
          limit: 15
          width_percent: 15      # 15% of terminal width
          min_width: 8           # Minimum 8 characters
          max_width: 20          # Maximum 20 characters
          visible: true
          alignment: "center"
          display_name: "Status"
        availability:
          limit: 15
          width_percent: 15      # 15% of terminal width
          min_width: 10          # Minimum 10 characters
          max_width: 20          # Maximum 20 characters
          visible: true
          alignment: "center"
          display_name: "Availability"
        role:
          limit: 10
          width_percent: 10      # 10% of terminal width
          min_width: 6           # Minimum 6 characters
          max_width: 15          # Maximum 15 characters
          visible: true
          alignment: "center"
          display_name: "Role"
        engine:
          limit: 25
          width_percent: 15      # 20% of terminal width
          min_width: 15          # Minimum 15 characters
          max_width: 35          # Maximum 35 characters
          visible: true
          alignment: "left"
          display_name: "Engine"
        manager_status:
          limit: 15
          width_percent: 15      # 15% of terminal width
          min_width: 10          # Minimum 10 characters
          max_width: 20          # Maximum 20 characters
          visible: true
          alignment: "center"
          display_name: "Manager Status"

    "Swarm Services":
      columns:
        id:
          limit: 12
          width_percent: 15      # 15% of terminal width
          min_width: 10          # Minimum 10 characters
          max_width: 20          # Maximum 20 characters
          visible: true
          alignment: "left"
          display_name: "Service ID"
        name:
          limit: 25
          width_percent: 30      # 30% of terminal width
          min_width: 15          # Minimum 15 characters
          max_width: 50          # Maximum 50 characters
          visible: true
          alignment: "left"
          display_name: "Service Name"
        mode:
          limit: 15
          width_percent: 15      # 15% of terminal width
          min_width: 10          # Minimum 10 characters
          max_width: 20          # Maximum 20 characters
          visible: true
          alignment: "center"
          display_name: "Mode"
        replicas:
          limit: 15
          width_percent: 15      # 15% of terminal width
          min_width: 8           # Minimum 8 characters
          max_width: 20          # Maximum 20 characters
          visible: true
          alignment: "center"
          display_name: "Replicas"
        image:
          limit: 35
          width_percent: 25      # 25% of terminal width
          min_width: 20          # Minimum 20 characters
          max_width: 50          # Maximum 50 characters
          visible: true
          alignment: "left"
          display_name: "Image"
