colors:
  header: "#00FF00"     # Bright green header
  border: "#444444"     # Dark gray borders
  text: "#E0E0E0"       # Light gray text
  background: "black"   # Black background
  success: "#00FF00"    # Bright green success
  warning: "#FFFF00"    # Bright yellow warning
  error: "#FF0000"      # Bright red error
  info: "#0080FF"       # Bright blue info

shell:
  border: "#444444"     # Dark gray borders (matching theme)
  title: "#00FF00"      # Bright green title (matching header)
  text: "#E0E0E0"       # Light gray text (matching theme)
  background: "black"   # Black background (matching theme)
  cmd:
    label: "#00FF00"      # Bright green label (matching success)
    border: "#444444"     # Dark gray border (matching theme)
    text: "#E0E0E0"       # Light gray text (matching theme)
    background: "black"   # Black background (matching theme)
    placeholder: "#666666" # Medium gray placeholder

containerExec:
  label: "#00FF00"      # Bright green label (matching header)
  border: "#444444"     # Dark gray border (matching theme)
  text: "#E0E0E0"       # Light gray text (matching theme)
  background: "#222222" # Very dark gray background
  placeholder: "#666666" # Medium gray placeholder (matching shell)
  title: "#00FF00"      # Bright green title (matching header)

commandMode:
  label: "#00FF00"      # Bright green label (matching header)
  border: "#444444"     # Dark gray border (matching theme)
  text: "#E0E0E0"       # Light gray text (matching theme)
  background: "#222222" # Very dark gray background
  placeholder: "#666666" # Medium gray placeholder (matching shell)
  title: "#00FF00"      # Bright green title (matching header)

# Character limits for table columns
tableLimits:
  id: 12          # Container/Image IDs
  name: 25        # Container/Volume names (reduced from 30)
  image: 35       # Image names (reduced from 40)
  status: 15      # Status messages (reduced from 20)
  state: 10       # State values (reduced from 15)
  ports: 20       # Port mappings (reduced from 25)
  created: 15     # Created timestamps (reduced from 20)
  size: 12        # Size values (reduced from 15)
  driver: 12      # Volume drivers (reduced from 15)
  mountpoint: 40  # Mount points (reduced from 50)
  repository: 30  # Image repositories (reduced from 35)
  tag: 15         # Image tags (reduced from 20)
  network: 20     # Network names (reduced from 25)
  scope: 10       # Network scope (reduced from 15)
  description: 40 # General descriptions (reduced from 50)
