// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDockerInfo creates a new instance of MockDockerInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDockerInfo(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockDockerInfo {
	mock := &MockDockerInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDockerInfo is an autogenerated mock type for the DockerInfo type
type MockDockerInfo struct {
	mock.Mock
}

type MockDockerInfo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDockerInfo) EXPECT() *MockDockerInfo_Expecter {
	return &MockDockerInfo_Expecter{mock: &_m.Mock}
}

// GetContainers provides a mock function for the type MockDockerInfo
func (_mock *MockDockerInfo) GetContainers() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContainers")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockDockerInfo_GetContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainers'
type MockDockerInfo_GetContainers_Call struct {
	*mock.Call
}

// GetContainers is a helper method to define mock.On call
func (_e *MockDockerInfo_Expecter) GetContainers() *MockDockerInfo_GetContainers_Call {
	return &MockDockerInfo_GetContainers_Call{Call: _e.mock.On("GetContainers")}
}

func (_c *MockDockerInfo_GetContainers_Call) Run(run func()) *MockDockerInfo_GetContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDockerInfo_GetContainers_Call) Return(n int) *MockDockerInfo_GetContainers_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockDockerInfo_GetContainers_Call) RunAndReturn(run func() int) *MockDockerInfo_GetContainers_Call {
	_c.Call.Return(run)
	return _c
}

// GetImages provides a mock function for the type MockDockerInfo
func (_mock *MockDockerInfo) GetImages() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetImages")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockDockerInfo_GetImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImages'
type MockDockerInfo_GetImages_Call struct {
	*mock.Call
}

// GetImages is a helper method to define mock.On call
func (_e *MockDockerInfo_Expecter) GetImages() *MockDockerInfo_GetImages_Call {
	return &MockDockerInfo_GetImages_Call{Call: _e.mock.On("GetImages")}
}

func (_c *MockDockerInfo_GetImages_Call) Run(run func()) *MockDockerInfo_GetImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDockerInfo_GetImages_Call) Return(n int) *MockDockerInfo_GetImages_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockDockerInfo_GetImages_Call) RunAndReturn(run func() int) *MockDockerInfo_GetImages_Call {
	_c.Call.Return(run)
	return _c
}

// GetLoggingDriver provides a mock function for the type MockDockerInfo
func (_mock *MockDockerInfo) GetLoggingDriver() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLoggingDriver")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDockerInfo_GetLoggingDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLoggingDriver'
type MockDockerInfo_GetLoggingDriver_Call struct {
	*mock.Call
}

// GetLoggingDriver is a helper method to define mock.On call
func (_e *MockDockerInfo_Expecter) GetLoggingDriver() *MockDockerInfo_GetLoggingDriver_Call {
	return &MockDockerInfo_GetLoggingDriver_Call{Call: _e.mock.On("GetLoggingDriver")}
}

func (_c *MockDockerInfo_GetLoggingDriver_Call) Run(run func()) *MockDockerInfo_GetLoggingDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDockerInfo_GetLoggingDriver_Call) Return(s string) *MockDockerInfo_GetLoggingDriver_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDockerInfo_GetLoggingDriver_Call) RunAndReturn(run func() string) *MockDockerInfo_GetLoggingDriver_Call {
	_c.Call.Return(run)
	return _c
}

// GetNetworks provides a mock function for the type MockDockerInfo
func (_mock *MockDockerInfo) GetNetworks() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNetworks")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockDockerInfo_GetNetworks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNetworks'
type MockDockerInfo_GetNetworks_Call struct {
	*mock.Call
}

// GetNetworks is a helper method to define mock.On call
func (_e *MockDockerInfo_Expecter) GetNetworks() *MockDockerInfo_GetNetworks_Call {
	return &MockDockerInfo_GetNetworks_Call{Call: _e.mock.On("GetNetworks")}
}

func (_c *MockDockerInfo_GetNetworks_Call) Run(run func()) *MockDockerInfo_GetNetworks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDockerInfo_GetNetworks_Call) Return(n int) *MockDockerInfo_GetNetworks_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockDockerInfo_GetNetworks_Call) RunAndReturn(run func() int) *MockDockerInfo_GetNetworks_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperatingSystem provides a mock function for the type MockDockerInfo
func (_mock *MockDockerInfo) GetOperatingSystem() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOperatingSystem")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDockerInfo_GetOperatingSystem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperatingSystem'
type MockDockerInfo_GetOperatingSystem_Call struct {
	*mock.Call
}

// GetOperatingSystem is a helper method to define mock.On call
func (_e *MockDockerInfo_Expecter) GetOperatingSystem() *MockDockerInfo_GetOperatingSystem_Call {
	return &MockDockerInfo_GetOperatingSystem_Call{Call: _e.mock.On("GetOperatingSystem")}
}

func (_c *MockDockerInfo_GetOperatingSystem_Call) Run(run func()) *MockDockerInfo_GetOperatingSystem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDockerInfo_GetOperatingSystem_Call) Return(s string) *MockDockerInfo_GetOperatingSystem_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDockerInfo_GetOperatingSystem_Call) RunAndReturn(run func() string) *MockDockerInfo_GetOperatingSystem_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function for the type MockDockerInfo
func (_mock *MockDockerInfo) GetVersion() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDockerInfo_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockDockerInfo_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
func (_e *MockDockerInfo_Expecter) GetVersion() *MockDockerInfo_GetVersion_Call {
	return &MockDockerInfo_GetVersion_Call{Call: _e.mock.On("GetVersion")}
}

func (_c *MockDockerInfo_GetVersion_Call) Run(run func()) *MockDockerInfo_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDockerInfo_GetVersion_Call) Return(s string) *MockDockerInfo_GetVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDockerInfo_GetVersion_Call) RunAndReturn(run func() string) *MockDockerInfo_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolumes provides a mock function for the type MockDockerInfo
func (_mock *MockDockerInfo) GetVolumes() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVolumes")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockDockerInfo_GetVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolumes'
type MockDockerInfo_GetVolumes_Call struct {
	*mock.Call
}

// GetVolumes is a helper method to define mock.On call
func (_e *MockDockerInfo_Expecter) GetVolumes() *MockDockerInfo_GetVolumes_Call {
	return &MockDockerInfo_GetVolumes_Call{Call: _e.mock.On("GetVolumes")}
}

func (_c *MockDockerInfo_GetVolumes_Call) Run(run func()) *MockDockerInfo_GetVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDockerInfo_GetVolumes_Call) Return(n int) *MockDockerInfo_GetVolumes_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockDockerInfo_GetVolumes_Call) RunAndReturn(run func() int) *MockDockerInfo_GetVolumes_Call {
	_c.Call.Return(run)
	return _c
}
