// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockImage creates a new instance of MockImage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImage(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockImage {
	mock := &MockImage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImage is an autogenerated mock type for the Image type
type MockImage struct {
	mock.Mock
}

type MockImage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImage) EXPECT() *MockImage_Expecter {
	return &MockImage_Expecter{mock: &_m.Mock}
}
