// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockVolume creates a new instance of MockVolume. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVolume(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockVolume {
	mock := &MockVolume{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVolume is an autogenerated mock type for the Volume type
type MockVolume struct {
	mock.Mock
}

type MockVolume_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVolume) EXPECT() *MockVolume_Expecter {
	return &MockVolume_Expecter{mock: &_m.Mock}
}
