// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/wikczerski/whaletui/internal/shared"

	mock "github.com/stretchr/testify/mock"
)

// NewMockVolumeService creates a new instance of MockVolumeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVolumeService(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockVolumeService {
	mock := &MockVolumeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVolumeService is an autogenerated mock type for the VolumeService type
type MockVolumeService struct {
	mock.Mock
}

type MockVolumeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVolumeService) EXPECT() *MockVolumeService_Expecter {
	return &MockVolumeService_Expecter{mock: &_m.Mock}
}

// GetActions provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) GetActions() map[rune]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActions")
	}

	var r0 map[rune]string
	if returnFunc, ok := ret.Get(0).(func() map[rune]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[rune]string)
		}
	}
	return r0
}

// MockVolumeService_GetActions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActions'
type MockVolumeService_GetActions_Call struct {
	*mock.Call
}

// GetActions is a helper method to define mock.On call
func (_e *MockVolumeService_Expecter) GetActions() *MockVolumeService_GetActions_Call {
	return &MockVolumeService_GetActions_Call{Call: _e.mock.On("GetActions")}
}

func (_c *MockVolumeService_GetActions_Call) Run(run func()) *MockVolumeService_GetActions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVolumeService_GetActions_Call) Return(runeToString map[rune]string) *MockVolumeService_GetActions_Call {
	_c.Call.Return(runeToString)
	return _c
}

func (_c *MockVolumeService_GetActions_Call) RunAndReturn(run func() map[rune]string) *MockVolumeService_GetActions_Call {
	_c.Call.Return(run)
	return _c
}

// GetActionsString provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) GetActionsString() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActionsString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockVolumeService_GetActionsString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActionsString'
type MockVolumeService_GetActionsString_Call struct {
	*mock.Call
}

// GetActionsString is a helper method to define mock.On call
func (_e *MockVolumeService_Expecter) GetActionsString() *MockVolumeService_GetActionsString_Call {
	return &MockVolumeService_GetActionsString_Call{Call: _e.mock.On("GetActionsString")}
}

func (_c *MockVolumeService_GetActionsString_Call) Run(run func()) *MockVolumeService_GetActionsString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVolumeService_GetActionsString_Call) Return(s string) *MockVolumeService_GetActionsString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockVolumeService_GetActionsString_Call) RunAndReturn(run func() string) *MockVolumeService_GetActionsString_Call {
	_c.Call.Return(run)
	return _c
}

// InspectVolume provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) InspectVolume(ctx context.Context, name string) (map[string]any, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for InspectVolume")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]any, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]any); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVolumeService_InspectVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InspectVolume'
type MockVolumeService_InspectVolume_Call struct {
	*mock.Call
}

// InspectVolume is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockVolumeService_Expecter) InspectVolume(ctx interface{}, name interface{}) *MockVolumeService_InspectVolume_Call {
	return &MockVolumeService_InspectVolume_Call{Call: _e.mock.On("InspectVolume", ctx, name)}
}

func (_c *MockVolumeService_InspectVolume_Call) Run(run func(ctx context.Context, name string)) *MockVolumeService_InspectVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVolumeService_InspectVolume_Call) Return(stringToV map[string]any, err error) *MockVolumeService_InspectVolume_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockVolumeService_InspectVolume_Call) RunAndReturn(run func(ctx context.Context, name string) (map[string]any, error)) *MockVolumeService_InspectVolume_Call {
	_c.Call.Return(run)
	return _c
}

// ListVolumes provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) ListVolumes(ctx context.Context) ([]shared.Volume, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListVolumes")
	}

	var r0 []shared.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]shared.Volume, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []shared.Volume); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]shared.Volume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVolumeService_ListVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVolumes'
type MockVolumeService_ListVolumes_Call struct {
	*mock.Call
}

// ListVolumes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVolumeService_Expecter) ListVolumes(ctx interface{}) *MockVolumeService_ListVolumes_Call {
	return &MockVolumeService_ListVolumes_Call{Call: _e.mock.On("ListVolumes", ctx)}
}

func (_c *MockVolumeService_ListVolumes_Call) Run(run func(ctx context.Context)) *MockVolumeService_ListVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVolumeService_ListVolumes_Call) Return(volumes []shared.Volume, err error) *MockVolumeService_ListVolumes_Call {
	_c.Call.Return(volumes, err)
	return _c
}

func (_c *MockVolumeService_ListVolumes_Call) RunAndReturn(run func(ctx context.Context) ([]shared.Volume, error)) *MockVolumeService_ListVolumes_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveVolume provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) RemoveVolume(ctx context.Context, name string, force bool) error {
	ret := _mock.Called(ctx, name, force)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVolume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, name, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVolumeService_RemoveVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveVolume'
type MockVolumeService_RemoveVolume_Call struct {
	*mock.Call
}

// RemoveVolume is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - force bool
func (_e *MockVolumeService_Expecter) RemoveVolume(ctx interface{}, name interface{}, force interface{}) *MockVolumeService_RemoveVolume_Call {
	return &MockVolumeService_RemoveVolume_Call{Call: _e.mock.On("RemoveVolume", ctx, name, force)}
}

func (_c *MockVolumeService_RemoveVolume_Call) Run(run func(ctx context.Context, name string, force bool)) *MockVolumeService_RemoveVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVolumeService_RemoveVolume_Call) Return(err error) *MockVolumeService_RemoveVolume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVolumeService_RemoveVolume_Call) RunAndReturn(run func(ctx context.Context, name string, force bool) error) *MockVolumeService_RemoveVolume_Call {
	_c.Call.Return(run)
	return _c
}
