// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLogsService creates a new instance of MockLogsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogsService {
	mock := &MockLogsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogsService is an autogenerated mock type for the LogsService type
type MockLogsService struct {
	mock.Mock
}

type MockLogsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogsService) EXPECT() *MockLogsService_Expecter {
	return &MockLogsService_Expecter{mock: &_m.Mock}
}

// GetActions provides a mock function for the type MockLogsService
func (_mock *MockLogsService) GetActions() map[rune]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActions")
	}

	var r0 map[rune]string
	if returnFunc, ok := ret.Get(0).(func() map[rune]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[rune]string)
		}
	}
	return r0
}

// MockLogsService_GetActions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActions'
type MockLogsService_GetActions_Call struct {
	*mock.Call
}

// GetActions is a helper method to define mock.On call
func (_e *MockLogsService_Expecter) GetActions() *MockLogsService_GetActions_Call {
	return &MockLogsService_GetActions_Call{Call: _e.mock.On("GetActions")}
}

func (_c *MockLogsService_GetActions_Call) Run(run func()) *MockLogsService_GetActions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogsService_GetActions_Call) Return(runeToString map[rune]string) *MockLogsService_GetActions_Call {
	_c.Call.Return(runeToString)
	return _c
}

func (_c *MockLogsService_GetActions_Call) RunAndReturn(run func() map[rune]string) *MockLogsService_GetActions_Call {
	_c.Call.Return(run)
	return _c
}

// GetActionsString provides a mock function for the type MockLogsService
func (_mock *MockLogsService) GetActionsString() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActionsString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockLogsService_GetActionsString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActionsString'
type MockLogsService_GetActionsString_Call struct {
	*mock.Call
}

// GetActionsString is a helper method to define mock.On call
func (_e *MockLogsService_Expecter) GetActionsString() *MockLogsService_GetActionsString_Call {
	return &MockLogsService_GetActionsString_Call{Call: _e.mock.On("GetActionsString")}
}

func (_c *MockLogsService_GetActionsString_Call) Run(run func()) *MockLogsService_GetActionsString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogsService_GetActionsString_Call) Return(s string) *MockLogsService_GetActionsString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockLogsService_GetActionsString_Call) RunAndReturn(run func() string) *MockLogsService_GetActionsString_Call {
	_c.Call.Return(run)
	return _c
}
